version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Australia/ACT
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: lxml
    versions:
    - 4.6.3
