kind: pipeline
type: docker
name: auspost

steps:
- name: pylint
  image: python:3.7
  commands:
  - pip install --quiet pipenv
  - pipenv install --dev
  # W0511 = TODO
  # W0707 = Raise-missing-from
  - pipenv run pylint --disable=W0511,W0707 auspost
- name: pytest
  image: python:3.7
  commands:
  - pip install --quiet pipenv
  - pipenv install --dev
  - pipenv run pytest test.py
